/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "primary-fixed-dim": "#b2c5ff",
        "on-primary-fixed-variant": "#0040a2",
        "inverse-primary": "#b2c5ff",
        "surface-container-high": "#e7e8ea",
        "surface-dim": "#d9dadc",
        "on-primary-fixed": "#001848",
        "tertiary": "#7b2600",
        "on-primary-container": "#c4d2ff",
        "surface-container": "#edeef0",
        "surface-tint": "#0c56d0",
        "error-container": "#ffdad6",
        "background": "#f8f9fb",
        "secondary-fixed-dim": "#c9bfff",
        "on-secondary": "#ffffff",
        "on-primary": "#ffffff",
        "surface": "#f8f9fb",
        "inverse-surface": "#2e3132",
        "tertiary-fixed": "#ffdbcf",
        "error": "#ba1a1a",
        "secondary-fixed": "#e5deff",
        "on-error-container": "#93000a",
        "surface-container-highest": "#e1e2e4",
        "primary-fixed": "#dae2ff",
        "primary": "#003d9b",
        "on-error": "#ffffff",
        "surface-variant": "#e1e2e4",
        "on-secondary-fixed": "#1a0063",
        "outline-variant": "#c3c6d6",
        "on-tertiary-fixed-variant": "#812800",
        "on-secondary-fixed-variant": "#4633a0",
        "inverse-on-surface": "#f0f1f3",
        "primary-container": "#0052cc",
        "on-tertiary-fixed": "#380d00",
        "tertiary-container": "#a33500",
        "surface-bright": "#f8f9fb",
        "on-surface": "#191c1e",
        "on-secondary-container": "#341d8d",
        "on-tertiary": "#ffffff",
        "tertiary-fixed-dim": "#ffb59b",
        "secondary-container": "#9f8eff",
        "surface-container-lowest": "#ffffff",
        "on-tertiary-container": "#ffc6b2",
        "outline": "#737685",
        "surface-container-low": "#f3f4f6",
        "on-surface-variant": "#434654",
        "secondary": "#5e4db9",
        "on-background": "#191c1e"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "sidebar-width": "260px",
        "stack-sm": "8px",
        "card-padding": "20px",
        "container-margin": "24px",
        "stack-md": "16px",
        "gutter": "16px"
      },
      fontFamily: {
        "headline-md": ["Manrope", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "label-sm": ["Inter", "sans-serif"],
        "display-metrics": ["Manrope", "sans-serif"],
        "metric-unit": ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "headline-lg": ["Manrope", "sans-serif"]
      },
      fontSize: {
        "headline-md": ["18px", { lineHeight: "24px", fontWeight: "600" }],
        "body-lg": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "label-sm": ["12px", { lineHeight: "16px", letterSpacing: "0.05em", fontWeight: "600" }],
        "display-metrics": ["36px", { lineHeight: "44px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "metric-unit": ["14px", { lineHeight: "20px", fontWeight: "500" }],
        "body-md": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "headline-lg": ["24px", { lineHeight: "32px", fontWeight: "600" }]
      }
    },
  },
  plugins: [],
}
